{
 "title": "Query Stream Cache",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{namespace=~\"$namespace\"},pod)"
    }
   },
   { "name": "query", "label": "Query", "query": { "query": "label_values(query)" } }
  ]
 },
 "panels": [
  {
   "title": "Number of subscribers",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_number_of_subscriptions{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of queries in cache",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_number_of_queries{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Abandoned Queries",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_number_of_abandoned_queries_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Documents",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_number_of_documents{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Queries vs Abandoned Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "cache_number_of_abandoned_queries_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Abandoned Queries - {{pod}}"
    },
    {
     "expr": "cache_number_of_queries{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Total Queries - {{pod}}"
    }
   ]
  },
  {
   "title": "Active Queries vs Abandoned Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "cache_number_of_queries{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}-cache_number_of_abandoned_queries_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Active Queries - {{pod}}"
    },
    {
     "expr": "cache_number_of_abandoned_queries_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Abandoned Queries - {{pod}}"
    }
   ]
  },
  {
   "title": "Number of Subscribers vs Queries ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "cache_number_of_subscriptions{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Subscribers - {{pod}}"
    },
    {
     "expr": "cache_number_of_queries{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Queries - {{pod}}"
    }
   ]
  },
  {
   "title": "Number of Subscribers vs Active Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "cache_number_of_subscriptions{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Subscribers - {{pod}}"
    },
    {
     "expr": "cache_number_of_queries{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}-cache_number_of_abandoned_queries_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Active Queries - {{pod}}"
    }
   ]
  },
  {
   "title": "Query Living Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_living_time{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\",query=~\"$query\"}",
     "legendFormat": "[{{query}}] - {{pod}}"
    }
   ]
  },
  {
   "title": "Number of Subscriber per Query",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "query_number_of_subscribers{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\",query=~\"$query\"}",
     "legendFormat": "Query Subscribers - [{{query}}] - {{pod}}"
    }
   ]
  },
  {
   "title": "Queries with living time less than 10 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "count(query_living_time{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}<=600)",
     "legendFormat": "Living time < 10 min"
    },
    {
     "expr": "count(query_living_time{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}>600)",
     "legendFormat": "Living time > 10 min"
    }
   ]
  },
  {
   "title": "Query Time Between Abandonment and Re-Subscription",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_time_between_abandonment_and_resubscription{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\",query=~\"$query\"}",
     "legendFormat": "[{{query}}] - {{pod}}"
    }
   ]
  },
  {
   "title": "Queries with Time Between Abandonment and Re-Subscription less than 10 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "count(query_time_between_abandonment_and_resubscription{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}<=600)",
     "legendFormat": "Time Between Abandonment and Re-Subscription < 10 min"
    },
    {
     "expr": "count(query_time_between_abandonment_and_resubscription{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}>600)",
     "legendFormat": "Time Between Abandonment and Re-Subscription > 10 min"
    }
   ]
  },
  {
   "title": "Cache Misses per Query > 1",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_cache_misses_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\",query=~\"$query\"}>1",
     "legendFormat": "[{{query}}] - {{pod}}"
    }
   ]
  },
  {
   "title": "Unique Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(query_cache_misses_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Queries > 1 Cache Miss",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(query_cache_misses_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}>1)"
    }
   ]
  },
  {
   "title": "Queries with > 1 Subscriber",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "count(query_number_of_subscribers{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}>1)",
     "legendFormat": "Number of Subscribers > 1"
    },
    {
     "expr": "count(query_number_of_subscribers{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}>0)",
     "legendFormat": "Total Number of Queries"
    }
   ]
  },
  {
   "title": "Histogram Test",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "cache_misses_total{namespace=~\"$namespace\",container=~\"$deployment\",pod=~\"$pod\"}",
     "legendFormat": "Cache Misses - {{pod}}"
    }
   ]
  }
 ]
}