{
 "title": "QueryStream overview",
 "tags": [ "querystream" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(querystream_clients_connected, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(querystream_clients_connected{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(querystream_subscriptions{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(querystream_queries{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_sum{namespace=\"$namespace\", consumergroup=\"querystream-dbmanager--multiple\"} >= 0)"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(querystream_clients_connected{namespace=\"$namespace\"})",
       "legendFormat": "clients"
      },
      {
       "expr": "sum(querystream_queries{namespace=\"$namespace\"})",
       "legendFormat": "queries"
      },
      {
       "expr": "sum(querystream_subscriptions{namespace=\"$namespace\"})",
       "legendFormat": "subscriptions"
      }
     ]
    },
    {
     "title": "Clients per instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(querystream_clients_connected{namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "dbmanager topic lag",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag_sum{namespace=\"$namespace\", consumergroup=\"querystream-dbmanager--multiple\"} >= 0) by (topic)",
       "legendFormat": "{{ topic }}"
      }
     ]
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Database Manager: Message processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(message_processed_duration_seconds_count{namespace=\"$namespace\", container=\"sa-component-querystream-dbmanager\"}[1m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Subscription: Message in/out from Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(querystream_queries_messages_received_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(querystream_subscriptions_messages_sent_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Database Manager: Processing time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(message_processed_duration_seconds_bucket{namespace=\"$namespace\", container=\"sa-component-querystream-dbmanager\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Subscription Manager: Processing time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(message_processed_duration_seconds_bucket{namespace=\"$namespace\", container=\"sa-component-querystream\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Infrastructure overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\", pod=~\"sa-component-querystream-[a-z0-9]{9,10}-[a-z0-9]{5}\"}) or vector(0)",
     "legendFormat": "subscription managers"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\", pod=~\"sa-component-querystream-dbmanager-[a-z0-9]{9,10}-[a-z0-9]{5}\"}) or vector(0)",
     "legendFormat": "database managers"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\", pod=~\"sa-component-querystream-feedmanager-[a-z0-9]{9,10}-[a-z0-9]{5}\"}) or vector(0)",
     "legendFormat": "feed managers"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\", pod=~\"sa-component-querystream-rest-[a-z0-9]{9,10}-[a-z0-9]{5}\"}) or vector(0)",
     "legendFormat": "rest"
    }
   ]
  },
  {
   "title": "Infrastructure: Subscription Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container=\"sa-component-querystream\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{unit=\"core\",namespace=~\"$namespace\",container=\"sa-component-querystream\"}",
     "legendFormat": "request"
    },
    {
     "expr": "kube_pod_container_resource_limits{unit=\"core\",namespace=~\"$namespace\",container=\"sa-component-querystream\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"$namespace\",container=\"sa-component-querystream\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{unit=\"byte\",namespace=~\"$namespace\",container=\"sa-component-querystream\"}",
     "legendFormat": "request"
    },
    {
     "expr": "kube_pod_container_resource_limits{unit=\"byte\",namespace=~\"$namespace\",container=\"sa-component-querystream\"}",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}