{
 "title": "All Environment Overview™",
 "tags": [ "environment-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "environment", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Infrastructure KPI's",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)/1024/1024",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "All Critical Alert",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "severity=\"critical\"",
     "filters": "severity=critical",
     "labelSelector": "*",
     "legendFormat": "All Critical Alert",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "All Warning Alert",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "severity=\"warning\"",
     "filters": "severity=warning",
     "labelSelector": "*",
     "legendFormat": "All Warning Alert",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  { "title": "${namespace}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$namespace",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 6 },
   "repeat": "namespace",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"coreapi-svc\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "request-per-sec"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=~\"$namespace\",code=~\"4..|5..\"}[5m]))/sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\"}[5m])) or vector(0)",
     "legendFormat": "error-rate"
    },
    {
     "expr": "sum(message_processed_duration_seconds_count{namespace=\"$namespace\", state=\"Error\"})/sum(message_processed_duration_seconds_count{namespace=\"$namespace\"}) or vector(0)",
     "legendFormat": "exception-rate"
    },
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"^$namespace$\"})",
     "legendFormat": "congestion"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=~\"$namespace\"}[5m]))/sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "api-response-time"
    },
    {
     "expr": "sum(ALERTS{namespace=\"$namespace\", severity=\"warning\"} or ALERTS{namespace=\"$namespace\", severity=\"warning\"}) or vector(0)",
     "legendFormat": "warning-alert"
    },
    {
     "expr": "sum(ALERTS{namespace=\"$namespace\", severity=\"critical\"} or ALERTS{namespace=\"$namespace\", severity=\"critical\"}) or vector(0)",
     "legendFormat": "critical-alert"
    },
    {
     "expr": "sum(rate(message_processed_duration_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "message-per-sec"
    }
   ]
  }
 ]
}