{
 "title": "Deployment status",
 "tags": [
  "application",
  "deployment"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "statefulset",
    "label": "StateFulSet",
    "query": {
     "query": "label_values(kube_statefulset_labels{namespace=~\"$namespace\"},statefulset)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Deployments $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$deployment",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "repeat": "deployment",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Available",
     "crit": 49,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "(sum by (deployment) (avg by (deployment) (kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=\"$deployment\"}))) / (sum by (deployment) (avg by (deployment) (kube_deployment_status_replicas{namespace=\"$namespace\",deployment=\"$deployment\"}))) * 100",
     "legendFormat": "Available",
     "units": "percent",
     "valueDisplayRegex": ".*",
     "valueHandler": "Number Threshold",
     "warn": 99
    },
    {
     "aggregation": "Last",
     "alias": "Desired",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (deployment) (avg by (deployment) (kube_deployment_status_replicas{namespace=\"$namespace\",deployment=\"$deployment\"}))",
     "legendFormat": "Desired",
     "units": "none",
     "valueDisplayRegex": ".*",
     "valueHandler": "Text Only"
    }
   ]
  },
  { "title": "Statefulsets $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$statefulset",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "repeat": "statefulset",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Available",
     "crit": 49,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "(avg by (statefulset)(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"$statefulset\"})) / (avg by (statefulset)(kube_statefulset_status_replicas{namespace=\"$namespace\", statefulset=\"$statefulset\"})) * 100",
     "legendFormat": "Available",
     "units": "percent",
     "valueDisplayRegex": ".*",
     "valueHandler": "Number Threshold",
     "warn": 99
    },
    {
     "aggregation": "Last",
     "alias": "Desired",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (statefulset) (avg by (statefulset) (kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=\"$statefulset\"}))",
     "legendFormat": "Desired",
     "units": "none",
     "valueDisplayRegex": ".*",
     "valueHandler": "Text Only"
    }
   ]
  },
  {
   "title": "Jobs $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Succeeded and failed jobs",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (kube_job_complete{namespace=\"$namespace\",condition=\"true\"}) ",
       "legendFormat": "Succeeded"
      },
      {
       "expr": "sum(kube_job_failed{namespace=\"$namespace\",condition=\"true\"})",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments Historic $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$deployment",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "repeat": "deployment",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (deployment) (avg by (deployment) (kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=\"$deployment\"}))"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Statefulsets Historic $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "$statefulset",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "repeat": "statefulset",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "alias": "Available",
       "crit": 49,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "(avg by (statefulset)(kube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"$statefulset\"}))",
       "legendFormat": "Available",
       "units": "percent",
       "valueDisplayRegex": ".*",
       "valueHandler": "Number Threshold",
       "warn": 99
      },
      {
       "aggregation": "Last",
       "alias": "Desired",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum by (statefulset) (avg by (statefulset) (kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=\"$statefulset\"}))",
       "legendFormat": "Desired",
       "units": "none",
       "valueDisplayRegex": ".*",
       "valueHandler": "Text Only"
      }
     ]
    }
   ]
  }
 ]
}