{
 "title": "Applications monitoring",
 "tags": [
  "application",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "instance",
    "label": "Kafka broker",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{kubernetes_namespace=~\"$namespace\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Kafka topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(http_requests_received_total{namespace=~\"^$namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General health metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unhealthy applications",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (min by (name) ((aspnetcore_healthcheck_status{namespace=~\"^$namespace$\"}) < (0.5))) or vector (0)"
    }
   ]
  },
  {
   "title": "Degraded applications",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (min by (name) ((aspnetcore_healthcheck_status{namespace=~\"^$namespace$\"}) < (1.0))) or vector (0)"
    }
   ]
  },
  {
   "title": "Health checks",
   "type": "graph",
   "description": "1 - healthy\n0.5 - degradaded\n0 - unhealthy",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    {
     "format": "short",
     "label": "3 - Unhealthy, 2 - Degradaded, 1 - Healthy"
    }
   ],
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{namespace=~\"^$namespace$\"}",
     "legendFormat": "{{ pod }} | {{ namespace}}"
    }
   ]
  },
  { "title": "General Kafka metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  { "title": "Specific app metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Requests per type and return code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "20X responses" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=~\"^$app\"}[1m])) by (method, code)",
     "legendFormat": "{{ method }} - {{ code }}"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{container=~\"^$app\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "API Request throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{container=~\"^$app\",namespace=~\"^$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 37 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{container=~\"^$app\", namespace=~\"^$namespace\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API Error %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{container=~\"^$app\",namespace=~\"$namespace\", code =~ \"5\\\\d\\\\d|\"}) / sum(http_requests_received_total{container=~\"^$app\",namespace=~\"$namespace\"})",
     "legendFormat": "5XX errors"
    },
    {
     "expr": "sum(http_requests_received_total{container=~\"^$app\",namespace=~\"$namespace\", code =~ \"4\\\\d\\\\d|\"}) / sum(http_requests_received_total{container=~\"^$app\",namespace=~\"$namespace\"})",
     "legendFormat": "4XX errors"
    }
   ]
  }
 ]
}