{
 "title": "Outbound Adapters",
 "description": "Overview and details of outbound adapters",
 "tags": [ "application" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Environment", "query": { "query": "label_values(namespace)" } },
   {
    "name": "container",
    "label": "Adapter",
    "query": {
     "query": "label_values(adapter_message_processing_duration_seconds_bucket,container)"
    }
   },
   {
    "name": "service_type",
    "label": "Service",
    "query": {
     "query": "label_values(adapter_message_received_total{container=\"$container\"},service_type)"
    }
   },
   {
    "name": "entity_set_name",
    "label": "EntitySetName",
    "query": {
     "query": "label_values(qs_client_actual_qs_request_duration_bucket{container=\"$container\"},entity_set_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FLIRT services status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flirt_last_time_service_started_seconds{namespace=\"$namespace\"} > bool on (container,service_type) (flirt_last_time_service_stopped_seconds{namespace=\"$namespace\"} or flirt_last_time_service_started_seconds{namespace=\"$namespace\"} * 0)",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "SAP services status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sap_last_time_service_started_seconds{namespace=\"$namespace\"} > bool on (container,service_type) (sap_last_time_service_stopped_seconds{namespace=\"$namespace\"} or sap_last_time_service_started_seconds{namespace=\"$namespace\"} * 0)",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last heartbeat succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - adapter_last_heartbeat_succeeded_timestamp_seconds{namespace=\"$namespace\"}",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last heartbeat failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (container, service_type) (time() - adapter_last_heartbeat_failed_timestamp_seconds{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last message received - operational data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by (container, service_type) (adapter_last_message_received_timestamp_seconds{namespace=\"$namespace\",service_type=~\"flight_data|flight_record|baggage_wait_time|prm_work_order|aviator|Schedules|Logbook\"})",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last message received - FLIRT/SAP daily master data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by (container, service_type) (adapter_last_message_received_timestamp_seconds{namespace=\"$namespace\",service_type=~\"Airlines|Handlers|Countries|FlightTypes|Airports\"})",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last message received - FLIRT/SAP non-daily master data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by (container, service_type) (adapter_last_message_received_timestamp_seconds{namespace=\"$namespace\",service_type=~\"AircraftTypes|Registrations\"})",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last request succeeded - operational data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (max by (container,service_type) (adapter_last_request_succeeded_timestamp_seconds{namespace=\"$namespace\",service_type=~\"flight_data|flight_record|baggage_wait_time|prm_work_order|aviator|Schedules|Logbook\"}))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last request succeeded - FLIRT/SAP daily master data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (max by (container,service_type) (adapter_last_request_succeeded_timestamp_seconds{namespace=\"$namespace\",service_type=~\"Airlines|Handlers|Countries|FlightTypes|Airports\"}))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last request succeeded - FLIRT/SAP non-daily master data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (max by (container,service_type) (adapter_last_request_succeeded_timestamp_seconds{namespace=\"$namespace\",service_type=~\"AircraftTypes|Registrations\"}))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Last request failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by (container,service_type) (adapter_last_request_failed_timestamp_seconds{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Kafka connection status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status{name=~\".*Kafka.*\",namespace=\"$namespace\",container=\"cph-adapter-edw\"}",
     "legendFormat": "EDW"
    },
    {
     "expr": "aspnetcore_healthcheck_status{name=~\".*Kafka.*\",namespace=\"$namespace\",container=\"sa-adapter-falck-prm\"}",
     "legendFormat": "Falck PRM Work Order"
    },
    {
     "expr": "aspnetcore_healthcheck_status{name=~\".*Kafka.*\",namespace=\"$namespace\",container=\"cph-adapter-aviator\"}",
     "legendFormat": "Aviator"
    }
   ]
  },
  {
   "title": "Query Stream subscription status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"FalckPRM\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"sa-adapter-falck-prm\",service_type=\"flight_data\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"FalckPRM\"} * 0)",
     "legendFormat": "{{container}}-flight_data"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"SasOutboundAdapterFLT\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-sasoutbound-flt\",service_type=\"SasOutboundAdapterFLT\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"SasOutboundAdapterFLT\"} * 0)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"SasOutboundAdapterBaggageWaitTime\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-sasoutbound-baggage\",service_type=\"SasOutboundAdapterBaggageWaitTime\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"SasOutboundAdapterBaggageWaitTime\"} * 0)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"AviatorAdapter\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-aviator\",service_type=\"aviator\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"AviatorAdapter\"} * 0)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"TowControlQsSubscription\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-nitos-towcontrol-a\",service_type=\"tow_control\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"TowControlQsSubscription\",container=\"cph-adapter-nitos-towcontrol-a\"} * 0)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"TowControlQsSubscription\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-nitos-towcontrol-b\",service_type=\"tow_control\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"TowControlQsSubscription\",container=\"cph-adapter-nitos-towcontrol-b\"} * 0)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Data received per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container,service_type) (increase(adapter_message_received_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Successful requests per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container,service_type) (increase(adapter_request_success_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Unsuccessful requests per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container,service_type) (increase(adapter_request_failure_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Message processing failures per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container,service_type) (increase(adapter_message_processing_failure_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Message processing duration 5 minute average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (container,service_type) (rate(adapter_message_processing_duration_seconds_sum{namespace=\"$namespace\"}[5m])) / (sum by (container,service_type) (rate(adapter_message_processing_duration_seconds_count{namespace=\"$namespace\"}[5m])))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Endpoint response duration 5 minute average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (container,service_type) (rate(adapter_server_response_duration_seconds_sum{namespace=\"$namespace\"}[5m])) / sum by (container,service_type)  (rate(adapter_server_response_duration_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Processing utilization per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (container, client_name) (rate(qs_client_subscriber_processing_milliseconds_total{namespace=\"$namespace\", mode!=\"idle\"}[1m])/10)\n",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Query Stream subscription initializations per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by (client_name) (increase(qs_client_subscription_initialization_started{namespace=\"$namespace\"}[5m]))\n",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Query Stream REST fetch fails per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (container, service_type) (increase(adapter_query_stream_fetch_failed_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{service_type}}"
    }
   ]
  },
  {
   "title": "Query Stream REST response duration 5 minute average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (container,entity_set_name) (rate(qs_client_actual_qs_request_duration_sum{namespace=\"$namespace\"}[5m]) / rate(qs_client_actual_qs_request_duration_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{entity_set_name}}"
    }
   ]
  },
  {
   "title": "Message processing duration for $container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }
  },
  {
   "title": "Service type: $service_type",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "repeat": "service_type",
   "targets": [
    {
     "expr": "sum (increase(adapter_message_processing_duration_seconds_bucket{namespace=\"$namespace\",container=\"$container\", service_type=\"$service_type\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Endpoint response duration for $container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "repeat": "container"
  },
  {
   "title": "Service type: $service_type",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum (increase(adapter_message_processing_duration_seconds_bucket{namespace=\"$namespace\",container=\"$container\", service_type=\"$service_type\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Stream REST response durations for $container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 }
  },
  {
   "title": "Entity set: $entity_set_name",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 95 },
   "repeat": "entity_set_name",
   "targets": [
    {
     "expr": "sum (increase(qs_client_actual_qs_request_duration_bucket{namespace=\"$namespace\",container=\"$container\", entity_set_name=\"$entity_set_name\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Status history", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "FLIRT services status history",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "flirt_last_time_service_started_seconds{namespace=\"$namespace\"} > bool on (container,service_type) (flirt_last_time_service_stopped_seconds{namespace=\"$namespace\"} or flirt_last_time_service_started_seconds{namespace=\"$namespace\"} * 0)",
     "legendFormat": "FLIRT {{service_type}}"
    }
   ]
  },
  {
   "title": "SAP services status history",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sap_last_time_service_started_seconds{namespace=\"$namespace\"} > bool on (container,service_type) (sap_last_time_service_stopped_seconds{namespace=\"$namespace\"} or sap_last_time_service_started_seconds{namespace=\"$namespace\"} * 0)",
     "legendFormat": "SAP {{service_type}}"
    }
   ]
  },
  {
   "title": "Amount of heartbeats successful per 5 minutes",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (container,service_type) (increase(adapter_heartbeat_success_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{service_type}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Amount of heartbeats failed per 5 minutes",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (container,service_type) (increase(adapter_heartbeat_failure_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{container}}-{{service_type}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Query Stream subscription status",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"FalckPRM\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"sa-adapter-falck-prm\",service_type=\"flight_data\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"FalckPRM\"} * 0)",
     "legendFormat": "{{container}}-flight_data"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"SasOutboundAdapterFLT\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-sasoutbound-flt\",service_type=\"SasOutboundAdapterFLT\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"SasOutboundAdapterFLT\"} * 0)",
     "legendFormat": "{{container}}-flight_record"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"SasOutboundAdapterBaggageWaitTime\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-sasoutbound-baggage\",service_type=\"SasOutboundAdapterBaggageWaitTime\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"SasOutboundAdapterBaggageWaitTime\"} * 0)",
     "legendFormat": "{{container}}-flight_record"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"AviatorAdapter\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-aviator\",service_type=\"aviator\"} or qs_client_last_time_subscription_initialization_started{namespace=\"test1\",client_name=\"AviatorAdapter\"} * 0)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"TowControlQsSubscription\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-nitos-towcontrol-a\",service_type=\"tow_control\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"TowControlQsSubscription\",container=\"cph-adapter-nitos-towcontrol-a\"} * 0)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (container) (qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"TowControlQsSubscription\"}) > bool on (container) max by (container) (adapter_last_query_stream_subscription_dropped_timestamp_seconds{namespace=\"$namespace\",container=\"cph-adapter-nitos-towcontrol-b\",service_type=\"tow_control\"} or qs_client_last_time_subscription_initialization_started{namespace=\"$namespace\",client_name=\"TowControlQsSubscription\",container=\"cph-adapter-nitos-towcontrol-b\"} * 0)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}