{
 "title": "AODB",
 "tags": [
  "application",
  "monitoring",
  "aodb"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aodb_pipeline_step_duration_seconds_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AODB Pipeline",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of invocations (per minute)"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(aodb_pipeline_duration_seconds_count{namespace=~\"$namespace\"}[1m])) by (namespace)",
     "legendFormat": "{{ kubernetes_namespace }} invocations"
    }
   ]
  },
  {
   "title": "Processing pr pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aodb_pipeline_duration_seconds_count{namespace=~\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Processing time per step",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum(rate(aodb_pipeline_step_duration_seconds_sum{namespace=~\"$namespace\"}[1m])) by (step)\n",
     "legendFormat": "{{ step }}"
    }
   ]
  }
 ]
}