{
 "title": "Application threads",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_threads, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=\"$namespace\", container!=\"\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=\"$namespace\", container=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=\"$namespace\", service!=\"\"}) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  }
 ]
}