{
 "title": "Cluster - requests and limits",
 "tags": [
  "application",
  "requests/limits"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})",
     "legendFormat": "CPU Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "Requests and limits per namespace",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Requests and limits per container",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"}) by (namespace, container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"}) by (namespace, container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) by (namespace, container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) by (namespace, container)"
    }
   ]
  }
 ]
}