{
 "title": "Inbound adapters - Message statistics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Messages published from message processors in $interval buckets",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container,topic) (increase(messaging_producer_publishes_total{namespace=\"$namespace\", state=\"Success\", topic=~\"traffic-planning-flightlegacd|traffic-operational-amsamadeus|traffic-operational-flightlegfomamadeus|traffic-operational-groundlegfomamadeus|traffic-operational-apfamadeus|traffic-operational-flightdataeurocontrol|traffic-operational-flightoperationcheckincounters|traffic-operational-dgsfos|traffic-operational-bagfos|traffic-operational-nitosflightlegfpl|traffic-operational-nitosgroundlegfpl|traffic-operational-nitosdeicesequencefpl|traffic-operational-nitosstatechangefpl|traffic-operational-maestrofpl|traffic-operational-coopansfpl|traffic-operational-a3000fpl|traffic-operational-admnorwegian|traffic-operational-radsas|traffic-operational-admsas|traffic-operational-codesharesas|traffic-operational-fuelsas|traffic-operational-ldmsas|traffic-operational-outboundemails|traffic-operational-iclsas|traffic-operational-mvtsas|traffic-operational-plesas|traffic-operational-groundradareventsicogroundradar|traffic-operational-palsita|traffic-operational-cpmsita|traffic-operational-ldmsita|traffic-operational-mvtsita|traffic-operational-palsita|traffic-operational-prlsita|traffic-operational-psmsita|traffic-operational-ptmsita|traffic-operational-ptsxovis\"}[$interval]))",
     "legendFormat": "{{topic}} - {{container}}"
    }
   ]
  },
  {
   "title": "Number of messages in total 1h buckets from processors",
   "type": "table",
   "gridPos": { "h": 25, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(messaging_producer_publishes_total{namespace=\"$namespace\", state=\"Success\", topic=~\"traffic-planning-flightlegacd|traffic-operational-amsamadeus|traffic-operational-flightlegfomamadeus|traffic-operational-groundlegfomamadeus|traffic-operational-apfamadeus|traffic-operational-flightdataeurocontrol|traffic-operational-flightoperationcheckincounters|traffic-operational-dgsfos|traffic-operational-bagfos|traffic-operational-nitosflightlegfpl|traffic-operational-nitosgroundlegfpl|traffic-operational-nitosdeicesequencefpl|traffic-operational-nitosstatechangefpl|traffic-operational-maestrofpl|traffic-operational-coopansfpl|traffic-operational-a3000fpl|traffic-operational-admnorwegian|traffic-operational-radsas|traffic-operational-admsas|traffic-operational-codesharesas|traffic-operational-fuelsas|traffic-operational-ldmsas|traffic-operational-outboundemails|traffic-operational-iclsas|traffic-operational-mvtsas|traffic-operational-plesas|traffic-operational-groundradareventsicogroundradar|traffic-operational-palsita|traffic-operational-cpmsita|traffic-operational-ldmsita|traffic-operational-mvtsita|traffic-operational-palsita|traffic-operational-prlsita|traffic-operational-psmsita|traffic-operational-ptmsita|traffic-operational-ptsxovis\"}[1h]))"
    }
   ]
  },
  {
   "title": "Messages published from endpoints in $interval buckets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (container,topic) (increase(messaging_producer_publishes_total{namespace=\"$namespace\", state=\"Success\", topic=~\"inbound-raw-scracd|inbound-raw-amsamadeus|inbound-raw-fomamadeus|inbound-raw-apfamadeus|inbound-raw-flightdataeurocontrol|inbound-raw-technicaleurocontrol|inbound-raw-flightoperationcheckincounters|inbound-raw-allfos|inbound-raw-fpl|inbound-raw-admnorwegian|inbound-raw-radsas|inbound-raw-admsas|inbound-raw-codesharesas|inbound-raw-fuelsas|inbound-raw-ldmsas|inbound-raw-ldmtelexsas|inbound-raw-ptmsas|inbound-raw-mvtsas|inbound-raw-groundradareventsicogroundradar|inbound-raw-palsita|inbound-raw-cpmsita|inbound-raw-ldmsita|inbound-raw-mvtsita|inbound-raw-palsita|inbound-raw-prlsita|inbound-raw-psmsita|inbound-raw-ptmsita|inbound-raw-ptsxovis\"}[$interval]))",
     "legendFormat": "{{topic}} - {{container}}"
    }
   ]
  }
 ]
}