{
 "title": "ADDS and FOS - Overview",
 "description": "Dashboard for the ADDS (Airhart ODDS) and FOS adapters",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "feed",
    "label": "Feed",
    "query": "Aircraft,AircraftType,Country,DeskAllocation1,FlightBaggageOperation,FlightOperation,FlightOperationAidx,FlightOperation4,FlightOperationLink,FlightOperation4Link,FlightOperationFlightPlan,Location,Operator"
   }
  ]
 },
 "panels": [
  {
   "title": "Feed Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "odds_feed_availability{namespace=\"$namespace\", feed=~\"($feed)( Feed)\"}",
     "legendFormat": "{{feed}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Rate of messages received from QS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (client_name, type_of_document,container,namespace,document_group) (rate(qs_client_number_of_documents_received_total{client_name=~\"(ODDS)($feed)(Dto)\", container=\"cph-adapter-odds\", namespace=\"$namespace\"}[1h]))",
     "legendFormat": "{{client_name}} - {{document_group}} - {{type_of_document}}"
    }
   ]
  },
  {
   "title": "Number of entries in cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "odds_total_number_of_entries_in_cache{namespace=\"$namespace\", feed=~\"($feed)(Dto)\"}",
     "legendFormat": "{{feed}} - {{typeOfCache}} - {{typeOfWindowOperation}}"
    }
   ]
  },
  {
   "title": "Number of requests for $feed feed",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(code) (round(increase(http_requests_received_total{namespace=\"$namespace\", container=\"cph-adapter-odds\", method=\"GET\", controller=\"$feed\"}[$__range])))"
    }
   ]
  }
 ]
}