{
 "title": "AODB Performance Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_brokers, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{namespace=\"$namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average processing time for namespace pr. container ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container) (rate(aodb_pipeline_duration_seconds_sum{namespace=~\"$namespace\", container=~\"$container\"}[5m])) / \nsum by (container) (rate(aodb_pipeline_duration_seconds_count{namespace=~\"$namespace\", container=~\"$container\"}[5m]))"
    }
   ]
  },
  {
   "title": "Avg. message Processing Time - in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(total_message_processing_duration_seconds_sum{namespace=~\"$namespace\", container=~\"$container\"}[1m])) by (container) /  \nsum(rate(total_message_processing_duration_seconds_count{namespace=~\"$namespace\", container=~\"$container\"}[1m])) by (container)",
     "legendFormat": "Avg. processing"
    }
   ]
  },
  {
   "title": "Pipelines Message Processing count pr. second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate(aodb_pipeline_runs_failed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m])  OR on() vector(0))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum (rate(aodb_pipeline_runs_cancelled_total{namespace=~\"$namespace\", container=~\"$container\"}[1m])  OR on() vector(0) )  ",
     "legendFormat": "Cancelled"
    },
    {
     "expr": "sum (rate(aodb_pipeline_runs_completed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m])  OR on() vector(0))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum (rate(aodb_pipeline_runs_failed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m]) OR on() vector(0) ) +\nsum (rate(aodb_pipeline_runs_cancelled_total{namespace=~\"$namespace\", container=~\"$container\"}[1m]) OR on() vector(0))   + \nsum (rate(aodb_pipeline_runs_completed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m]) OR on() vector(0)) ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (rate(aodb_pipeline_runs_failed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m]) OR on() vector(0) ) +\nsum (rate(aodb_pipeline_runs_cancelled_total{namespace=~\"$namespace\", container=~\"$container\"}[1m]) OR on() vector(0))   + \nsum (rate(aodb_pipeline_runs_completed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m]) OR on() vector(0)) ",
     "legendFormat": "Total (1h)"
    }
   ]
  },
  {
   "title": "Topic lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum( (kafka_consumergroup_lag{namespace=~\"$namespace\", topic=~\"traffic-operational-entityvalue-enrichment-default|traffic-operational-entityvalue-recalculation-default|traffic-operational-entityvalue-enrichment-priority|traffic-operational-entityvalue-enrichment-ui|traffic-operational-entityvalue-recalculation-priority|traffic-operational-entityvalue-recalculation-ui|aodb-pipeline-output|aodb-pipeline-dtd|aodb-background-job|qs-aodb-pipeline-output|aodb-system-message-update\"} OR on() vector(0) ) ) by (topic) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Incoming Messages on TOT pr. second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(message_tried_published{namespace=\"$namespace\", state=\"Success\", topic=~\"traffic-operational-a3000fpl|traffic-operational-admnorwegian|traffic-operational-admsas|traffic-operational-amsamadeus|traffic-operational-apfamadeus|traffic-operational-bagfos|traffic-operational-codesharesas|traffic-operational-coopansfpl|traffic-operational-cpmsita|traffic-operational-dgsfos|traffic-operational-flightdataeurocontrol|traffic-operational-flightlegfomamadeus|traffic-operational-flightoperationcheckincounters|traffic-operational-fuelsas|traffic-operational-groundlegfomamadeus|traffic-operational-groundradareventsicogroundradar|traffic-operational-iclsas|traffic-operational-ldmsas|traffic-operational-ldmsita|traffic-operational-maestrofpl|traffic-operational-mvtsas|traffic-operational-mvtsita|traffic-operational-nitosdeicesequencefpl|traffic-operational-nitosflightlegfpl|traffic-operational-nitosgroundlegfpl|traffic-operational-nitosstatechangefpl|traffic-operational-outboundemails|traffic-operational-palsita|traffic-operational-plesas|traffic-operational-prlsita|traffic-operational-psmsita|traffic-operational-ptmsita|traffic-operational-ptsxovis|traffic-operational-radsas|traffic-planning-flightlegacd\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(message_tried_published{namespace=\"$namespace\", state=\"Success\", topic=~\"traffic-operational-a3000fpl|traffic-operational-admnorwegian|traffic-operational-admsas|traffic-operational-amsamadeus|traffic-operational-apfamadeus|traffic-operational-bagfos|traffic-operational-codesharesas|traffic-operational-coopansfpl|traffic-operational-cpmsita|traffic-operational-dgsfos|traffic-operational-flightdataeurocontrol|traffic-operational-flightlegfomamadeus|traffic-operational-flightoperationcheckincounters|traffic-operational-fuelsas|traffic-operational-groundlegfomamadeus|traffic-operational-groundradareventsicogroundradar|traffic-operational-iclsas|traffic-operational-ldmsas|traffic-operational-ldmsita|traffic-operational-maestrofpl|traffic-operational-mvtsas|traffic-operational-mvtsita|traffic-operational-nitosdeicesequencefpl|traffic-operational-nitosflightlegfpl|traffic-operational-nitosgroundlegfpl|traffic-operational-nitosstatechangefpl|traffic-operational-outboundemails|traffic-operational-palsita|traffic-operational-plesas|traffic-operational-prlsita|traffic-operational-psmsita|traffic-operational-ptmsita|traffic-operational-ptsxovis|traffic-operational-radsas|traffic-planning-flightlegacd\"}[$__rate_interval]))",
     "legendFormat": "Total (1h)"
    },
    {
     "expr": "rate(message_tried_published{namespace=\"$namespace\", state=\"Success\", topic=~\"traffic-operational-a3000fpl|traffic-operational-admnorwegian|traffic-operational-admsas|traffic-operational-amsamadeus|traffic-operational-apfamadeus|traffic-operational-bagfos|traffic-operational-codesharesas|traffic-operational-coopansfpl|traffic-operational-cpmsita|traffic-operational-dgsfos|traffic-operational-flightdataeurocontrol|traffic-operational-flightlegfomamadeus|traffic-operational-flightoperationcheckincounters|traffic-operational-fuelsas|traffic-operational-groundlegfomamadeus|traffic-operational-groundradareventsicogroundradar|traffic-operational-iclsas|traffic-operational-ldmsas|traffic-operational-ldmsita|traffic-operational-maestrofpl|traffic-operational-mvtsas|traffic-operational-mvtsita|traffic-operational-nitosdeicesequencefpl|traffic-operational-nitosflightlegfpl|traffic-operational-nitosgroundlegfpl|traffic-operational-nitosstatechangefpl|traffic-operational-outboundemails|traffic-operational-palsita|traffic-operational-plesas|traffic-operational-prlsita|traffic-operational-psmsita|traffic-operational-ptmsita|traffic-operational-ptsxovis|traffic-operational-radsas|traffic-planning-flightlegacd\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "enrichment-priority lag on partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\", consumergroup=~\"aodb-pipeline\", topic=~\"traffic-operational-entityvalue-enrichment-priority\"}) by (topic, partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(up{namespace=~\"$namespace\",container=~\"sa-component-aodb-pipeline-priority|sa-component-aodb-pipeline-default|sa-component-aodb-pipeline-ui\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}