{
 "title": "AODB Message Processing Performance",
 "description": "Dashboard to work on improvements for AODB processing.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_brokers, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pipeline pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{namespace=\"$namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average processing time for namespace pr. container ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container) (rate(aodb_pipeline_duration_seconds_sum{namespace=~\"$namespace\", container=~\"$container\"}[5m])) / \nsum by (container) (rate(aodb_pipeline_duration_seconds_count{namespace=~\"$namespace\", container=~\"$container\"}[5m]))"
    }
   ]
  },
  {
   "title": "Lag Overview for Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{namespace=\"$namespace\", consumergroup=~\"aodb-pipeline|aodb--background-services\"}"
    }
   ]
  },
  {
   "title": "Step average processing times - Selected Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n(sum by (pod,step) (rate(aodb_pipeline_step_duration_seconds_sum{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]))) / \n(sum by (pod,step) (rate(aodb_pipeline_step_duration_seconds_count{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]))) \n)",
     "legendFormat": "{{pod}} Total"
    },
    {
     "expr": "(sum by (pod,step) (rate(aodb_pipeline_step_duration_seconds_sum{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]))) / \n(sum by (pod,step) (rate(aodb_pipeline_step_duration_seconds_count{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]))) \n",
     "legendFormat": "{{pod}} {{step}}"
    }
   ]
  },
  {
   "title": "Topic lag",
   "type": "timeseries",
   "description": "Topics rele",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\", topic=~\"traffic-operational-entityvalue-enrichment-default|traffic-operational-entityvalue-recalculation-default|traffic-operational-entityvalue-enrichment-priority|traffic-operational-entityvalue-enrichment-ui|traffic-operational-entityvalue-recalculation-priority|traffic-operational-entityvalue-recalculation-ui|aodb-pipeline-output|aodb-pipeline-dtd|aodb-background-job|qs-aodb-pipeline-output|aodb-system-message-update\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Pipelines Message Processing count pr. min - Selected Pods",
   "type": "timeseries",
   "description": "aodb_pipeline_runs_ [Completed, Cancelled, Failed]",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum (increase(aodb_pipeline_runs_failed_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "Failed messages"
    },
    {
     "expr": "sum (increase(aodb_pipeline_runs_cancelled_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]) )",
     "legendFormat": "Cancelled messages"
    },
    {
     "expr": "sum (increase(aodb_pipeline_runs_failed_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]) ) +\nsum (increase(aodb_pipeline_runs_cancelled_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]) ) + \nsum (increase(aodb_pipeline_runs_completed_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]) ) ",
     "legendFormat": "Total Messages"
    },
    {
     "expr": "sum (rate(aodb_pipeline_runs_completed_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[1m]) * 60) ",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Message Processing in Seconds",
   "type": "timeseries",
   "description": "Processing time from it is received in the adapter to it has been processed in the AODB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(total_message_processing_duration_seconds_sum{namespace=~\"$namespace\"}[1m])) /  \nsum(rate(total_message_processing_duration_seconds_count{namespace=~\"$namespace\"}[1m]))  "
    }
   ]
  },
  {
   "title": "Pipelines Message Processing count pr. min",
   "type": "timeseries",
   "description": "aodb_pipeline_runs_ [Completed, Cancelled, Failed]",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum (increase(aodb_pipeline_runs_failed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m])  OR on() vector(0))",
     "legendFormat": "Failed messages"
    },
    {
     "expr": "sum (increase(aodb_pipeline_runs_cancelled_total{namespace=~\"$namespace\", container=~\"$container\"}[1m])  OR on() vector(0) )  ",
     "legendFormat": "Cancelled messages"
    },
    {
     "expr": "sum (increase(aodb_pipeline_runs_failed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m]) OR on() vector(0) ) +\nsum (increase(aodb_pipeline_runs_cancelled_total{namespace=~\"$namespace\", container=~\"$container\"}[1m]))   + \nsum (increase(aodb_pipeline_runs_completed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m])) ",
     "legendFormat": "Total Messages"
    },
    {
     "expr": "sum (increase(aodb_pipeline_runs_completed_total{namespace=~\"$namespace\", container=~\"$container\"}[1m])  OR on() vector(0)) ",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "CPU Usage Seconds pr. namespace",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "core" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=~\"$container\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Incoming Messages on TOT pr. min",
   "type": "timeseries",
   "description": "Incoming Messages on Traffic Operational Topics",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(message_tried_published{namespace=\"$namespace\", state=\"Success\", topic=~\"traffic-operational-a3000fpl|traffic-operational-admnorwegian|traffic-operational-admsas|traffic-operational-amsamadeus|traffic-operational-apfamadeus|traffic-operational-bagfos|traffic-operational-codesharesas|traffic-operational-coopansfpl|traffic-operational-cpmsita|traffic-operational-dgsfos|traffic-operational-flightdataeurocontrol|traffic-operational-flightlegfomamadeus|traffic-operational-flightoperationcheckincounters|traffic-operational-fuelsas|traffic-operational-groundlegfomamadeus|traffic-operational-groundradareventsicogroundradar|traffic-operational-iclsas|traffic-operational-ldmsas|traffic-operational-ldmsita|traffic-operational-maestrofpl|traffic-operational-mvtsas|traffic-operational-mvtsita|traffic-operational-nitosdeicesequencefpl|traffic-operational-nitosflightlegfpl|traffic-operational-nitosgroundlegfpl|traffic-operational-nitosstatechangefpl|traffic-operational-outboundemails|traffic-operational-palsita|traffic-operational-plesas|traffic-operational-prlsita|traffic-operational-psmsita|traffic-operational-ptmsita|traffic-operational-ptsxovis|traffic-operational-radsas|traffic-planning-flightlegacd\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(message_tried_published{namespace=\"$namespace\", state=\"Success\", topic=~\"traffic-operational-a3000fpl|traffic-operational-admnorwegian|traffic-operational-admsas|traffic-operational-amsamadeus|traffic-operational-apfamadeus|traffic-operational-bagfos|traffic-operational-codesharesas|traffic-operational-coopansfpl|traffic-operational-cpmsita|traffic-operational-dgsfos|traffic-operational-flightdataeurocontrol|traffic-operational-flightlegfomamadeus|traffic-operational-flightoperationcheckincounters|traffic-operational-fuelsas|traffic-operational-groundlegfomamadeus|traffic-operational-groundradareventsicogroundradar|traffic-operational-iclsas|traffic-operational-ldmsas|traffic-operational-ldmsita|traffic-operational-maestrofpl|traffic-operational-mvtsas|traffic-operational-mvtsita|traffic-operational-nitosdeicesequencefpl|traffic-operational-nitosflightlegfpl|traffic-operational-nitosgroundlegfpl|traffic-operational-nitosstatechangefpl|traffic-operational-outboundemails|traffic-operational-palsita|traffic-operational-plesas|traffic-operational-prlsita|traffic-operational-psmsita|traffic-operational-ptmsita|traffic-operational-ptsxovis|traffic-operational-radsas|traffic-planning-flightlegacd\"}[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Memory Usage Seconds for Pod",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "core" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"$namespace\",container=~\"$container\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Enrichment-Priority - Lag per partition",
   "type": "barchart",
   "description": "Lag per topic partition. \nTopic : traffic-operational-entityvalue-enrichment-priority\nConsumergroup: aodb-pipeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\", consumergroup=~\"aodb-pipeline\", topic=~\"traffic-operational-entityvalue-enrichment-priority\"}) by (topic, partition)"
    }
   ]
  },
  {
   "title": "Enrichment-Default - Lag per partition",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\", consumergroup=~\"aodb-pipeline\", topic=~\"traffic-operational-entityvalue-enrichment-default\"}) by (topic, partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Recalculation-Default - Lag per partition",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\", consumergroup=~\"aodb-pipeline\", topic=~\"traffic-operational-entityvalue-recalculation-default\"}) by (topic, partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Recalculation-Default - Lag per partition",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\", consumergroup=~\"aodb-pipeline\", topic=~\"traffic-operational-entityvalue-recalculation-priority\"}) by (topic, partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Enrichment-UI - Lag per partition",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\", consumergroup=~\"aodb-pipeline\", topic=~\"traffic-operational-entityvalue-enrichment-ui\"}) by (topic, partition)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Adapter Topic lag",
   "type": "timeseries",
   "description": "Lag on adapter topics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\", topic=~\"traffic-planning-flightlegacd|traffic-operational-amsamadeus|traffic-operational-flightlegfomamadeus|traffic-operational-groundlegfomamadeus|traffic-operational-apfamadeus|traffic-operational-flightdataeurocontrol|traffic-operational-flightoperationcheckincounters|traffic-operational-dgsfos|traffic-operational-bagfos|traffic-operational-nitosflightlegfpl|traffic-operational-nitosgroundlegfpl|traffic-operational-nitosdeicesequencefpl|traffic-operational-nitosstatechangefpl|traffic-operational-maestrofpl|traffic-operational-coopansfpl|traffic-operational-a3000fpl|traffic-operational-admnorwegian|traffic-operational-radsas|traffic-operational-admsas|traffic-operational-codesharesas|traffic-operational-fuelsas|traffic-operational-ldmsas|traffic-operational-outboundemails|traffic-operational-iclsas|traffic-operational-mvtsas|traffic-operational-plesas|traffic-operational-groundradareventsicogroundradar|traffic-operational-palsita|traffic-operational-cpmsita|traffic-operational-ldmsita|traffic-operational-mvtsita|traffic-operational-palsita|traffic-operational-prlsita|traffic-operational-psmsita|traffic-operational-ptmsita|traffic-operational-ptsxovis\", consumergroup=\"aodb-pipeline\"}) by (topic) >= 0\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Skipped Messages",
   "type": "timeseries",
   "description": "Count of skipped messages pr. type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "sum(increase(skipped_messages_due_to_filter_total{namespace=~\"$namespace\"}[1m])) by (messageType)"
    }
   ]
  },
  {
   "title": "Concurrency conflights",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "sum (rate(aodb_pipeline_concurrency_conflicts_total{namespace=\"$namespace\"}[1m])*60) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage for Pods in Namespace",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short", "label": "core" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}