{
 "title": "External-DNS",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Source (kubeAPI) total and error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "external_dns_source_endpoints_total"
    },
    {
     "expr": "external_dns_source_errors_total"
    }
   ]
  },
  {
   "title": "Registry (DNS provider) total and error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "external_dns_registry_endpoints_total"
    },
    {
     "expr": "external_dns_registry_errors_total"
    }
   ]
  },
  {
   "title": "Last sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "external_dns_controller_last_sync_timestamp_seconds"
    }
   ]
  }
 ]
}