{
 "title": "Redis Cluster",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Custer", "query": { "query": "label_values(redis_up,job)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_uptime_in_seconds{job=\"redis-westeurope-redis-cluster-metrics\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "redis_up{job=\"$cluster\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Master",
   "type": "natel-discrete-panel",
   "description": "Masters have non-zero connected slaves",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "redis_connected_slaves{job=\"$cluster\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{job=\"$cluster\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{job=\"$cluster\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}-hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{job=\"$cluster\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}-misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"$cluster\",namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "redis_config_maxmemory{job=\"$cluster\",namespace=~\"$namespace\"} ",
     "legendFormat": "{{pod}}-max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{job=\"$cluster\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}-input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{job=\"$cluster\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}-output"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=\"$cluster\",namespace=~\"$namespace\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=\"$cluster\",namespace=~\"$namespace\"}) - sum (redis_db_keys_expiring{job=\"$cluster\",namespace=~\"$namespace\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{job=\"$cluster\",namespace=~\"$namespace\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{job=\"$cluster\",namespace=~\"$namespace\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{job=\"$cluster\",namespace=~\"$namespace\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{job=\"$cluster\",namespace=~\"$namespace\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  }
 ]
}