{
 "title": "Node performance",
 "tags": [
  "infrastructure",
  "kubernetes",
  "node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by ()(avg by (mode)(clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m]),1))) * 100,100)"
    }
   ]
  },
  {
   "title": "Average memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance,nodename) (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info) * 100)\r"
    }
   ]
  },
  {
   "title": "CPU top 10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,(sum by(nodename) ((clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m]), 1) * 100) * on(instance) group_left(nodename) node_uname_info) / (sum by(nodename) (label_replace(kube_node_status_allocatable_cpu_cores, \"nodename\", \"$1\", \"node\", \"(.*)\")))))\n\r",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory top 10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,(sum by (instance,nodename) (((node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info) * 100))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU bottom 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bottomk(10,(sum by(nodename) ((clamp_max(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m]), 1) * 100) * on(instance) group_left(nodename) node_uname_info) / (sum by(nodename) (label_replace(kube_node_status_allocatable_cpu_cores, \"nodename\", \"$1\", \"node\", \"(.*)\")))))\n\r",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory bottom 10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bottomk(10,(sum by (instance,nodename) (((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * on(instance) group_left(nodename) node_uname_info) * 100))",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}