{
 "title": "FluentBit",
 "description": "This is a simple dashboard for Fluent-bit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit input bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_input_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluent-bit output bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluent-bit error/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_errors_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries/fails",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_retries_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "Retries {{ pod }}/{{name}}"
    },
    {
     "expr": "rate(fluentbit_output_retries_failed_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "Failed {{ pod }}/{{name}}"
    }
   ]
  }
 ]
}