{
 "title": "Messaging overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_brokers, namespace)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{namespace=\"$namespace\", topic!~\"__.+\"}, topic)"
    }
   },
   {
    "name": "consumergroup",
    "label": "Consumer group",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset_sum{namespace=\"$namespace\", topic=~\"$topic\" $transient}, consumergroup)"
    }
   },
   {
    "name": "transient",
    "label": "Transient consumer groups",
    "query": "Hide : \\, consumergroup!~\".+-[0-9a-f]{9\\,10}-[0-9a-z]{5}$\"\\, consumergroup!~\".+-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\", Show : \\, consumergroup=~\".*\""
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Consumer errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_errors_total{namespace=\"$namespace\"} or vector(0)"
    }
   ]
  },
  {
   "title": "Under-replicated partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partition_under_replicated_partition{namespace=\"$namespace\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members{namespace=\"$namespace\", consumergroup=~\"$consumergroup\"})"
    }
   ]
  },
  {
   "title": "Messages produced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "count:msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=~\"$topic\"}[5m]))"
    }
   ]
  },
  {
   "title": "Messages consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "count:msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset_sum{namespace=\"$namespace\", consumergroup=~\"$consumergroup\", topic=~\"$topic\"}[5m]))"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "count:msg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=\"$namespace\", consumergroup=~\"$consumergroup\", topic=~\"$topic\"} > 0)"
    }
   ]
  },
  {
   "title": "Outbox lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "count:msg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(messaging_publisher_outbox_rows_in_table{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Consumer group lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=\"$namespace\", consumergroup=~\"$consumergroup\", topic=~\"$topic\"} >= 0) by (consumergroup, topic) unless (max_over_time(kafka_consumergroup_lag_sum{namespace=\"$namespace\", consumergroup=~\"$consumergroup\", topic=~\"$topic\"}[$__range])==0)",
     "legendFormat": "{{ consumergroup }} (topic: {{ topic }})"
    }
   ]
  },
  {
   "title": "Messages produced (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=~\"$topic\", topic!~\"__.+\"}[1m]) > 0) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Messages consumed (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_consumergroup_current_offset_sum{namespace=\"$namespace\", consumergroup=~\"$consumergroup\", topic=~\"$topic\", topic!~\"__.+\"}[1m]) > 0) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup }} (topic: {{ topic }})"
    }
   ]
  },
  { "title": "Message Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Processing performance",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(messaging_consumer_processed_duration_seconds_bucket{namespace=\"$namespace\", topic=~\"$topic\", consumergroup=~\"$consumergroup\", exception=\"\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Consume latency",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(messaging_consumer_latency_duration_seconds_bucket{namespace=\"$namespace\", topic=~\"$topic\", consumergroup=~\"$consumergroup\", exception=\"\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Message latency",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(messaging_message_latency_duration_seconds_bucket{namespace=\"$namespace\", topic=~\"$topic\", consumergroup=~\"$consumergroup\", exception=\"\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Processing exceptions (1 minute buckets)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(messaging_consumer_processed_duration_seconds_count{namespace=\"$namespace\", consumergroup=~\"$consumergroup\", topic=~\"$topic\", exception!=\"\"}[1m])) by (exception)",
     "legendFormat": "{{ exception }}"
    }
   ]
  },
  {
   "title": "Retries per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(increase(messaging_consumer_retries_total{namespace=\"$namespace\", topic=~\"$topic\", consumergroup=~\"$consumergroup\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Retries delay in seconds per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(increase(messaging_consumer_retry_delay_total{namespace=\"$namespace\", topic=~\"$topic\", consumergroup=~\"$consumergroup\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Number of skipped messages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum(increase(messaging_consumer_skipped_total{namespace=\"$namespace\", topic=~\"$topic\", consumergroup=~\"$consumergroup\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Component outbox", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Outbox lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(messaging_publisher_outbox_rows_in_table{namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Outbox latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "sum(increase(messaging_publisher_outbox_duration_seconds_bucket{namespace=\"$namespace\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}