{
 "title": "Messaging Partition Lag",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_brokers, namespace)"
    }
   },
   {
    "name": "consumergroup",
    "label": "Consumer group",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{namespace=\"$namespace\"}, consumergroup)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{namespace=\"$namespace\", consumergroup=\"$consumergroup\"}, topic)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{namespace=\"$namespace\", consumergroup=\"$consumergroup\", topic=\"$topic\"}, partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Produced vs. consumed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kafka_topic_partition_current_offset{namespace=\"$namespace\", topic=\"$topic\", partition=~\"$partition\"}[$__interval]))",
     "legendFormat": "produced"
    },
    {
     "expr": "sum(increase(kafka_consumergroup_current_offset{namespace=\"$namespace\", topic=\"$topic\", partition=~\"$partition\", consumergroup=\"$consumergroup\"}[$__interval])) * -1",
     "legendFormat": "consumed"
    },
    {
     "expr": "sum(clamp_min(kafka_consumergroup_lag{namespace=\"$namespace\", topic=\"$topic\", partition=~\"$partition\", consumergroup=\"$consumergroup\"},0))",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Processing exceptions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(messaging_consumer_processed_duration_seconds_count{namespace=\"$namespace\", consumergroup=\"$consumergroup\", topic=\"$topic\", exception!=\"\"}[1m])>0) by (exception)",
     "legendFormat": "{{ exception }}"
    }
   ]
  },
  {
   "title": "Lag on partitions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(clamp_min(kafka_consumergroup_lag{namespace=\"$namespace\", consumergroup=\"$consumergroup\", topic=\"$topic\", partition=~\"$partition\"},0)) by (partition)",
     "legendFormat": "{{ partition }}"
    }
   ]
  }
 ]
}