{
 "title": "Prometheus Operator Overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(prometheus_operator_syncs,controller)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,10m,30m,1h,6h,12h" }
  ]
 },
 "panels": [
  { "title": "General Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{container=\"prometheus-operator\",namespace=\"monitoring\"} * 1000"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_operator_build_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Managed replicas",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "displayType": "Regular",
     "expr": "prometheus_operator_spec_replicas{controller=~\"$controller\"}",
     "legendFormat": "{{name}}",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Prometheus Controller Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller)(prometheus_operator_ready{controller=~\"$controller\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Operator syncs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (prometheus_operator_syncs{controller=~\"$controller\",status=\"ok\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Operator failed syncs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (prometheus_operator_syncs{controller=~\"$controller\",status=\"failed\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Prometheuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "displayType": "Regular",
     "expr": "prometheus_operator_spec_shards{controller=~\"$controller\"}",
     "legendFormat": "{{name}}",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Managed resources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (resource) (prometheus_operator_managed_resources{state=\"selected\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Managed resources rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (resource) (prometheus_operator_managed_resources{state=\"rejected\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Kubernetes Client Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Requests Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code)(rate(prometheus_operator_kubernetes_client_http_requests_total[$interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests Duration Sum Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (endpoint)(rate(prometheus_operator_kubernetes_client_http_request_duration_seconds_sum[$interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Duration Count Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (endpoint)(rate(prometheus_operator_kubernetes_client_http_request_duration_seconds_count[$interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Rate Limiter Duration Sum Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (endpoint)(rate(prometheus_operator_kubernetes_client_rate_limiter_duration_seconds_sum[$interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Rate Limiter Duration Count Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (endpoint)(rate(prometheus_operator_kubernetes_client_rate_limiter_duration_seconds_count[$interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Node Syncs Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (container)(rate(prometheus_operator_node_syncs_total[$interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Alertmanagerconfig Trigger Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(prometheus_operator_alertmanager_config_validation_triggered_total[$interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Prometheus Rules Validation Trigger Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum by (container)(rate(prometheus_operator_rule_validation_triggered_total[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Reconcile Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (controller) (rate(prometheus_operator_reconcile_operations_total{controller=~\"$controller\"}[$interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Operation Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "sum by (controller)(prometheus_operator_reconcile_operations_total{controller=~\"$controller\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Statefulset Recreation Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by (controller) (rate(prometheus_operator_reconcile_sts_delete_create_total{controller=~\"$controller\"}[$interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Statefulset Recreation Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "targets": [
    {
     "expr": "sum by (controller)(prometheus_operator_reconcile_sts_delete_create_total{controller=~\"$controller\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Watch Operations Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (controller)(prometheus_operator_watch_operations_total{controller=~\"$controller\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Watch Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by (controller)(rate(prometheus_operator_watch_operations_total{controller=~\"$controller\"}[$interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "Failures Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Reconcile Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum by (controller)(rate(prometheus_operator_reconcile_errors_total{controller=~\"$controller\"}[$interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Watch Operation Fail Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 62 },
   "targets": [
    {
     "expr": "sum by (controller)(rate(prometheus_operator_watch_operations_failed_total{controller=~\"$controller\"}[$interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Prometheus Rules Validation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum by (container)(rate(prometheus_operator_rule_validation_errors_total[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Alertmanagerconfig Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 62 },
   "targets": [
    {
     "expr": "sum by (container)(rate(prometheus_operator_alertmanager_config_validation_errors_total[$interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "List Operation Fail Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum by (controller)(rate(prometheus_operator_list_operations_failed_total{controller=~\"$controller\"}[$interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Node IP Address Lookup Fail Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "sum by (controller)(rate(prometheus_operator_node_address_lookup_errors_total{controller=~\"$controller\"}[$interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Node Syncs Fail Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "sum by (container)(rate(prometheus_operator_node_syncs_failed_total[$interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}