{
 "title": "Fluentd",
 "description": "fluentd 1.x deployed in kubernetes and scraped by prometheus",
 "tags": [ "fluentd" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Buffer with Closest Estimated Time to Full - Based on Daily Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(1,\n(\n    (fluentd_output_status_buffer_available_space_ratio < 5)\n    / \n    (rate(fluentd_output_status_buffer_available_space_ratio[1d]))\n) < 60 * 60 * 24 * 4\n)",
     "legendFormat": "{{pod}} {{type}}"
    }
   ]
  },
  {
   "title": "Estimated Time Until Full Buffer Graph - Based on Daily Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "clamp_max(\n    ((fluentd_output_status_buffer_available_space_ratio < 5)\n    / \n    (rate(fluentd_output_status_buffer_available_space_ratio [1d]))),\n    60* 60 * 24 * 4\n)",
     "legendFormat": "{{pod}} {{type}}"
    }
   ]
  },
  {
   "title": "Fluentd output error/retry rate",
   "type": "graph",
   "description": "If you see errors then you probbaly have serious issues with log processing, see https://docs.fluentd.org/buffer#handling-unrecoverable-errors\n\nRetries are normal but should occur only from time to time, otherwise check for network errors or destination is too slow and requires additional tuning per given provider.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count[1m]))",
     "legendFormat": "Retry rate"
    },
    {
     "expr": "sum(rate(fluentd_output_status_num_errors[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Input /  output rate",
   "type": "graph",
   "description": "Input  and output total rates",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total[1m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(fluentd_output_status_write_count[1m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "fluentd output status buffer available space ratio",
   "type": "graph",
   "description": "This should not reach 0 otherwise logs are blocked from processing or even dropped",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(fluentd_output_status_buffer_available_space_ratio)",
     "legendFormat": "lowest across all hosts"
    }
   ]
  },
  {
   "title": "fluentd output status flush time count rate",
   "type": "graph",
   "description": "total flush time",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_flush_time_count[1m]))",
     "legendFormat": "time"
    },
    {
     "expr": "sum(rate(fluentd_output_status_slow_flush_count[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Current total size of stage and queue buffers.",
   "type": "graph",
   "description": "Current total size of stage and queue buffers.\nfluentd_output_status_buffer_total_bytes",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_total_bytes) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd output buffer queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_queue_length)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Input details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input entries rate (total)",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[1m])) ",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Input entries rate per hostname",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[1m])) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Input entries rate per namespace",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[1m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Input entries rate per instance",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[1m])) by (instance)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Input details (warning, very slow!)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input entries rate per tag",
     "type": "graph",
     "description": "fluentd_input_status_num_records_total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_input_status_num_records_total[1m])) by (tag)",
       "legendFormat": "{{tag}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Stage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current length of stage buffers.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_stage_length",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_stage_length) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    },
    {
     "title": "Current total size of stage buffers.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_stage_byte_size",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_stage_byte_size) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    }
   ]
  },
  { "title": "Buffer Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Maximum buffer length in last 1min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_buffer_queue_length[1m])",
     "legendFormat": "{{pod}} {{ type }}"
    }
   ]
  },
  {
   "title": "Maximum buffer bytes in last 1min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_buffer_total_bytes[1m])",
     "legendFormat": "{{pod}} {{ type }}"
    }
   ]
  },
  {
   "title": "Current length of queue buffers.",
   "type": "graph",
   "description": "fluentd_output_status_buffer_queue_length",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_queue_length) by (pod, type)",
     "legendFormat": "{{pod}} {{ type }}"
    }
   ]
  },
  {
   "title": "Current total size of queue buffers.",
   "type": "graph",
   "description": "fluentd_output_status_queue_byte_size",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_queue_byte_size) by (pod, type)",
     "legendFormat": "{{pod}} {{ type }}"
    }
   ]
  },
  { "title": "Buffer Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Ratio of available space in buffer.",
   "type": "graph",
   "description": "fluentd_output_status_buffer_available_space_ratio",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_available_space_ratio) by (pod, type)",
     "legendFormat": "{{pod}} {{ type }}"
    }
   ]
  },
  { "title": "Buffer Retries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Current retry counts.",
   "type": "graph",
   "description": "fluentd_output_status_retry_count",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current emit records",
   "type": "graph",
   "description": "fluentd_output_status_emit_records",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_records[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current emit counts rate",
   "type": "graph",
   "description": "fluentd_output_status_emit_count",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_count[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current rollback counts",
   "type": "graph",
   "description": "fluentd_output_status_rollback_count",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_rollback_count[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current write counts",
   "type": "graph",
   "description": "fluentd_output_status_write_count",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_write_count[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current slow flush counts",
   "type": "graph",
   "description": "fluentd_output_status_slow_flush_count",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_slow_flush_count[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current retry wait",
   "type": "graph",
   "description": "fluentd_output_status_retry_wait",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_wait[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total flush time",
   "type": "graph",
   "description": "fluentd_output_status_flush_time_count",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_flush_time_count[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Buffer Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Current number of errors rate",
   "type": "graph",
   "description": "fluentd_output_status_num_errors",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_errors[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Buffer timekeys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timekey diff",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "fluentd_output_status_buffer_newest_timekey - fluentd_output_status_buffer_oldest_timekey",
       "legendFormat": "{{pod}} {{ type}}"
      }
     ]
    },
    {
     "title": "Newest timekey in buffer.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_newest_timekey",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_newest_timekey) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    },
    {
     "title": "Oldest timekey in buffer.",
     "type": "graph",
     "description": "fluentd_output_status_buffer_oldest_timekey",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_oldest_timekey) by (pod, type)",
       "legendFormat": "{{pod}} {{ type }}"
      }
     ]
    }
   ]
  }
 ]
}