{
 "title": "Kafka",
 "description": "kafka_export dashboard",
 "tags": [
  "infrastructure",
  "Kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_brokers, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_brokers, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_brokers{job=~\"$job\"}, job)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{job='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Topic Partition Oldest Offset",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,{job=\"$instance\", topic=~\"$topic\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Topic Partition Current Offset",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{job=\"$instance\", topic=~\"$topic\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{job=\"$instance\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "kafka_consumergroup_members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members{job=\"$instance\", namespace=~\"$namespace\"}) by (consumergroup)",
     "legendFormat": "{{ consumergroup }}"
    }
   ]
  },
  {
   "title": "Leader Broker ID",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_leader{job=\"$instance\", topic=~\"$topic\", namespace=~\"$namespace\"}) by (topic, partition)",
     "legendFormat": "{topic=\"{{ topic }}\", partition=\"{{ partition}}\"}"
    }
   ]
  },
  {
   "title": "In Sync Replica",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{job=\"$instance\", topic=~\"$topic\", namespace=~\"$namespace\"}) by (topic, partition)",
     "legendFormat": "{topic=\"{{ topic }}\", partition=\"{{ partition}}\"}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{job=\"$instance\",topic=~\"$topic\", namespace=~\"$namespace\"} > 0) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_topic_partition_replicas{job=\"$instance\", topic=~\"$topic\", namespace=~\"$namespace\"}) by (topic, partition)",
     "legendFormat": "{topic=\"{{ topic }}\", partition=\"{{ partition}}\"}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{job=~\"$instance\",topic=~\"$topic\", namespace=~\"$namespace\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{job=\"$instance\",topic=~\"$topic\", namespace=~\"$namespace\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{job=~\"$instance\", topic=~\"$topic\", namespace=~\"$namespace\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Offset",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_oldest_offset{job=\"$instance\", topic=~\"$topic\", namespace=~\"$namespace\"}) by (partition,topic)"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{job=\"$instance\", topic=~\"$topic\", namespace=~\"$namespace\"}) by (partition,topic)"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{job=\"$instance\",topic=~\"$topic\", namespace=~\"$namespace\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}